# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TzAINw8g2x890JYMeLdDW4CGwZQs0igJ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import streamlit as st

# 데이터 불러오기
# Assuming the file is in the root of your Google Drive
df = pd.read_excel('/content/drive/MyDrive/data_journalism/AI_면접_도입_국내기업_35개.xlsx', index_col=0)
st.write('다음 데이터는 국내 주요 기업의 AI 면접 도입 현황을 집계한 것이다')
#st.write(df)

# 검색어 입력 받아 데이터 선택적으로 출력
query = st.text_input('이 곳에 회사명을 입력하면 관련 데이터만 검색해 보여줍니다', key='region1_input')
df_filtered = df[df.index.str.contains(query, na=False)]
st.write('검색 결과:', df_filtered)